const baseUrl = "/comunichE-Giamo"
document.write("<!DOCTYPE html>");
document.write("<html lang=\"it\">");
document.write("");
document.write("<head>");
document.write("    <meta charset=\"utf-8\">");
document.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">");
document.write("");
document.write("    <title>comunichE\/Giamo<\/title>");
document.write("    <meta content=\"\" name=\"description\">");
document.write("    <meta content=\"\" name=\"keywords\">");
document.write("");
document.write("    <!-- Favicons -->");
document.write("    <link href=\"assets\/img\/favicon.png\" rel=\"icon\">");
document.write("    <link href=\"assets\/img\/apple-touch-icon.png\" rel=\"apple-touch-icon\">");
document.write("");
document.write("    <!-- Google Fonts -->");
document.write("    <link rel=\"preconnect\" href=\"https:\/\/fonts.googleapis.com\">");
document.write("    <link rel=\"preconnect\" href=\"https:\/\/fonts.gstatic.com\" crossorigin>");
document.write("    <link href=\"https:\/\/fonts.googleapis.com\/css2?family=Roboto+Slab:wght@100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">");
document.write("");
document.write("    <!-- CDN Bootstrap -->");
document.write("    <link href=\"https:\/\/cdn.jsdelivr.net\/npm\/bootstrap@5.3.3\/dist\/css\/bootstrap.min.css\" rel=\"stylesheet\">");
document.write("    <script src=\"https:\/\/cdn.jsdelivr.net\/npm\/bootstrap@5.3.3\/dist\/js\/bootstrap.bundle.min.js\"><\/script>");
document.write("");
document.write("    <!-- Vendor CSS Files -->");
document.write("    <link href=\"assets\/vendor\/aos\/aos.css\" rel=\"stylesheet\">");
document.write("    <link href=\"assets\/vendor\/bootstrap-icons\/bootstrap-icons.css\" rel=\"stylesheet\">");
document.write("    <link href=\"assets\/vendor\/boxicons\/css\/boxicons.min.css\" rel=\"stylesheet\">");
document.write("    <link href=\"assets\/vendor\/glightbox\/css\/glightbox.min.css\" rel=\"stylesheet\">");
document.write("    <link href=\"assets\/vendor\/remixicon\/remixicon.css\" rel=\"stylesheet\">");
document.write("    <link href=\"assets\/vendor\/swiper\/swiper-bundle.min.css\" rel=\"stylesheet\">");
document.write("");
document.write("    <!-- Template Main CSS File -->");
document.write("    <link href=\"assets\/css\/style.css\" rel=\"stylesheet\">");
document.write("");
document.write("    <!-- Comunichegiamo Main CSS File -->");
document.write("    <link href=\"custom.css?v=1.3\" rel=\"stylesheet\">");
document.write("");
document.write("    <link rel=\"stylesheet\" href=\"https:\/\/unpkg.com\/leaflet@1.9.4\/dist\/leaflet.css\"\/>");
document.write("    <script src=\"https:\/\/unpkg.com\/leaflet@1.9.4\/dist\/leaflet.js\"><\/script>");
document.write("");
document.write("<\/head>");
document.write("");
document.write("<body>");
document.write("");
document.write("<!-- ======= Header ======= -->");
document.write("<header id=\"header\" class=\"fixed-top \">");
document.write("    <div class=\"container d-flex align-items-center\">");
document.write("");
document.write("        <h1 class=\"logo me-auto\"><a href=\"index.html\">comunich<strong>E\/G<\/strong>iamo<\/a><\/h1>");
document.write("        <!--<a href=\"index.html\" class=\"logo me-auto\"><img src=\"assets\/img\/logo.webp\" alt=\"\" class=\"img-fluid\"><\/a>-->");
document.write("");
document.write("        <nav id=\"navbar\" class=\"navbar navbarmobilecustom\">");
document.write("            <ul>");
document.write("                <li><a class=\"nav-link scrollto active\" href=\""+baseUrl+"\#hero\">Home<\/a><\/li>");
document.write("                <li><a class=\"nav-link scrollto\" href=\""+baseUrl+"\#portfolio\">Scatti<\/a><\/li>");
document.write("                <li><a class=\"nav-link scrollto\" href=\""+baseUrl+"\#team\">Chi siamo<\/a><\/li>");
document.write("                <li><a class=\"nav-link scrollto\" href=\""+baseUrl+"\#footer\">Social<\/a><\/li>");
document.write("                <li><a class=\"getstarted scrollto\" href=\""+baseUrl+"\#about\">La nostra IMPRESA<\/a><\/li>");
document.write("            <\/ul>");
document.write("            <i class=\"bi bi-list mobile-nav-toggle\"><\/i>");
document.write("        <\/nav><!-- .navbar -->");
document.write("");
document.write("    <\/div>");
document.write("<\/header><!-- End Header -->");
